### ISSUE TITLE
Add `/projects` subfolders to VS Code explorer when opening the workspace

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#20569]
### Is your task related to a problem? Please describe

Currently, when I start my workspace with Che-Code as an editor, there's no folder opened. I need to open `/projects` manually to open my imported project sources.

![image](https://user-images.githubusercontent.com/1636395/135623295-294394b3-5bb4-4e18-ae92-c91d90df5f6f.png)

### Describe the solution you'd like

Need to investigate how to configure Che-Code editor to open `/projects` subfolders as the workspace folders.

### Additional context

This issue is a part of the epic #20500

**Comment by azatsarynnyy** [comment]
The backend parameter that [I've used](https://github.com/che-incubator/che-code/pull/2) in my previous solution has [gone in upstream](https://github.com/microsoft/vscode/commit/74b3fc397d140bab6fc91f0c8a0911ee0530c495#diff-294102d93b173606d76ae7c0f5828010ecf75fbf68675f7afdbc2f49395827eb).
Need to investigate how to provide the initial folder from the frontend side, via the URL query parameter.

**Comment by azatsarynnyy** [comment]
As I understand, it's already fixed by a commit https://github.com/che-incubator/che-code/commit/4efae765c3134961552da706782cee62d8e489ee
@benoitf please, reopen it if I'm wrong.

**Comment by benoitf** [comment]
you're not wrong 👍 
I'm still not sure if it's as fast as the option we had on the server side but at least it's working again without deep changes 👍
