### ISSUE TITLE
Devworkspace - generateName in devfile throws error

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse/che#21067]
### Describe the bug

`generateName` property does not work. It seems that something broke during the work of v1 to v2 conversion.

```
Failed to create a workspace. Failed to create a new workspace from the devfile, reason: Failed to create a new workspace. Unable to create devworkspace: DevWorkspace.workspace.devfile.io "devfile-test" is invalid: [<nil>: Invalid value: "": "spec.template.components" must validate one and only one schema (oneOf). Found none valid, spec.template.components.container: Required value, spec.template.components.name: Invalid value: "": spec.template.components.name in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$']
```

![image](https://user-images.githubusercontent.com/15126675/150971417-c5f8299a-8f76-454b-92fe-8ad6df2f9eb8.png)

Devfile i used:

```
schemaVersion: 2.1.0
metadata:
  generateName: devfile-test
components:
  - name: nodejsdev
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-b452131
      endpoints:
        - exposure: public
          name: nodejs
          protocol: http
          targetPort: 3000
      memoryLimit: 1G
      mountSources: true
```

### Che version

7.42@latest

### Steps to reproduce

Run a devfile that should generate the workspaces' name.

### Expected behavior

Generate a name as described by https://devfile.io/docs/devfile/2.1.0/user-guide/adding-a-name-to-a-devfile.html.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

### Additional context

Running next-version of devworkspace-operator.

**Comment by l0rd** [comment]
Thank you @nils-mosbach for reporting this issue. If you are interested in contributing a fix the libary that does the v1 to v2 convertion is [here](https://github.com/che-incubator/devfile-converter). 
cc @benoitf

**Comment by benoitf** [comment]
I think I already fixed that in the converter library but the upgrade of the devfile converter library in che is still pending on https://github.com/eclipse-che/che-dashboard/pull/441

I'll check

**Comment by benoitf** [comment]
closing as new library has been integrated.

**Comment by nils-mosbach** [comment]
@benoitf Tried with `main` branch and issue still exists. 

Problem is that checks are handled in che-dashboard. 
https://github.com/eclipse-che/che-dashboard/blob/f9c2a7c087871c6095b033729c51729f779f252c/packages/dashboard-frontend/src/services/devfileApi/typeguards.ts#L26-L28

Previously che-dashboard generated a name if `generateName` was given.  Not sure why this was limited to older devfiles.

I'll drop a PR with a possible solution that works in my case.
