### ISSUE TITLE
Remove "Verbose" mode from UD

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22391]
### Is your enhancement related to a problem? Please describe

Verbose mode is not working and is pretty much useless since we have logs and events Tabs now on the dashboard. 

### Describe the solution you'd like

Remove "Verbose" mode from the UD

### Describe alternatives you've considered

N/A

### Additional context

Docs PR - https://github.com/eclipse-che/che-docs/pull/2636

**Comment by tolusha** [comment]
It is needed to remove from the doc as well https://eclipse.dev/che/docs/stable/end-user-guide/investigating-failures-at-a-workspace-start-using-the-verbose-mode/

**Comment by olexii4** [comment]
@ibuziuk  What about ```controller.devfile.io/debug-start: 'true'``` ?
![Знімок екрана 2023-08-08 о 11 25 27](https://github.com/eclipse/che/assets/6310786/a0842adb-fafb-49c7-92b8-67ff4a85acf1)
Should we remove it at all?

**Comment by ibuziuk** [comment]
@amisevsk could you please clarify how `"controller.devfile.io/debug-start=true"` annotation currently work on DWO end? does it makes sense to have "Debug" mode exposed on UD? What events logs would be propagated if the annotation is enabled?

**Comment by amisevsk** [comment]
Debugging startup is still useful, in my opinion. When that annotation is applied to a workspace, DWO prevents the workspace from stopping when it fails -- instead it enters a `Failing` state but is still marked as "started" on the cluster.

The purpose of this annotation is to debug workspace failures; when the annotation is present, DWO will not clean up any workspace resources until you tell it to (by setting `.spec.started: false` or removing the annotation). This allows you to view e.g. pod logs, or the pod spec, which is normally lost when a workspace enters the stopped phase. It's even more useful when automatic cleaning up of resources is enabled as in that case there are no resources left for the stopped workspace (e.g. no metadata configmap).

Documentation on the annotation is here: https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#debugging-a-failing-workspace

The intended flow is
1. Workspace fails
2. Apply annotation, restart workspace and let it fail again
3. Collect debugging information
4. Remove annotation to let workspace stop naturally

I'm not opposed to removing it from the Dashboard, as it's a flow that might require additional guidance (e.g. around removing the annotation when you're done debugging) but it's a fairly useful feature in genereal IMO.

**Comment by l0rd** [comment]
This issue has been fixed so I think we can close this one.

Having a way to set `controller.devfile.io/debug-start=true` from the dashboard is useful (a lot for us, less for a normal Che user) but it deserves it's own issue and a UX discussion.

**Comment by olexii4** [comment]
@ibuziuk We still have the ability to set `controller.devfile.io/debug-start=true from the dashboard`:
![Знімок екрана 2023-08-30 о 14 46 31](https://github.com/eclipse/che/assets/6310786/19c8ddcf-9961-48bd-bba7-4a5f4f27e958)
![Знімок екрана 2023-08-30 о 14 46 42](https://github.com/eclipse/che/assets/6310786/2f7ee962-522b-4a64-922e-1cd15a2834ef)
![Знімок екрана 2023-08-30 о 14 47 58](https://github.com/eclipse/che/assets/6310786/dac1e0ca-8a4b-4200-8f0e-872a7253afc3)

**Comment by ibuziuk** [comment]
@l0rd do you think we should leave it as is for now or also remove ^

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/22465
@l0rd @Kasturi1820 please review ^
